### ISSUE TITLE
appears to be broken?

### ISSUE THREAD

**Issue by managingwholes** [heigeo/climata#10]
Can't make climata work. Installed it some weeks ago and now get "can't find module named io" even though I had wq.io installed.

then I tried reinstalling climata:

Downloading/unpacking https://github.com/heigeo/climata.git
  Downloading climata.git (unknown size): 11kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 278, in ru
n
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundl
e=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python3/dist-packages/pip/download.py", line 582, in unpack_htt
p_url
    unpack_file(temp_location, location, content_type, link)
  File "/usr/lib/python3/dist-packages/pip/util.py", line 645, in unpack_file
    and is_svn_page(file_contents(filename))):
  File "/usr/lib/python3/dist-packages/pip/util.py", line 211, in file_contents
    return fp.read().decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid
start byte

**Comment by sheppard** [comment]
You should be able to install the latest stable version from PyPI (`pip3 install climata`) - though see #3.  If you want to install the development version you can do it with the github archive URL:
https://github.com/heigeo/climata/archive/master.zip

To use the main repository url (as you did here) you apparently need to tell pip it's a "git" url:
```
pip3 install git+https://github.com/heigeo/climata.git
```
